# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RFBase-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RFBase-iOS
  pod 'Turbolinks', :git => 'https://github.com/turbolinks/turbolinks-ios.git', :branch => 'swift-3.0'

  target 'RFBase-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RFBase-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
